version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dep/npm"
    labels: ["dep/npm"]
    ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-patch"]
