version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dep/yarn"
    labels: ["dep/yarn"]
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dep/flutter"
    labels: ["dep/flutter"]
    ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-minor"]
