name: Code QA

on:
  push:
    branches:
      - main
    paths:
      - 'api/**.ts'
      - 'api/package.json'
  pull_request:
    branches:
      - main
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.2'
    - name: Install dependencies
      run: |
        yarn cache clean
        yarn install --update-checksums
        yarn install
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
    - name: Run QA checks
      continue-on-error: true
      run: |
        cd api
        yarn run lint
    - name: Commit changes
      continue-on-error: true
      run: |
        git add .
        git commit -m "[auto]: Fix code style"
        git push
    - name: Rerun QA checks
      continue-on-error: true
      run: |
        cd api
        yarn run lint
        yarn audit
        