name: API Code QA

on:
  push:
    branches:
      - main
    paths:
      - 'api/**.ts'
      - 'api/package.json'
  pull_request:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  lint:

    runs-on: ubuntu-latest
    env:
      working-directory: ./api
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: Install dependencies
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: install
    - name: Configure Git
      run: |
        cd ..
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
    - name: Run QA checks
      continue-on-error: true
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: lint
    - name: Commit changes
      continue-on-error: true
      run: |
        cd ..
        git add .
        git reset api/yarn.lock
        git reset api/.yarnrc.yml
        git reset api/package.json
        git commit -m "[auto]: Fix code style"
        git push
    - name: Rerun QA checks
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: lint