name: Build Flutter app on Linux

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
      - 'analysis_options.yaml'
      - 'pubspec.yaml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
        channel: 'stable'
     - name: Install required system dependencies
       run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - name: Enable Linux support
       run: flutter config --enable-linux-desktop
     - name: Lint Dart code
       run: flutter analyze
     - name: Build Flutter app
       run: flutter build linux
