name: Code QA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.9'
    - name: Install dependencies
      run: |
        yarn install
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
    - name: Show problems
      continue-on-error: true
      run: |
        yarn run lint
    - name: Autofix problems
      run: |
        yarn run standard --fix
    - name: Show unresolved problems
      run: |
        yarn run lint
    - name: Commit changes
      continue-on-error: true
      run: |
        git add .
        git commit -m "[auto]: Fix code style"
        git push
        