name: Flutter Code QA

on:
  push:
    branches:
      - main
    paths:
      - '**.dart'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
        channel: 'stable'
     - name: Configure Git
       run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
     - name: Install dependencies
       run: flutter pub get
     - name: Run QA checks
       continue-on-error: true
       run: |
        flutter analyze
        dart fix --apply
        dart format .
     - name: Commit changes
       continue-on-error: true
       run: |
        git add .
        git reset pubspec.lock
        git commit -m "[auto]: Fix code style"
        git push
     - name: Rerun QA checks
       run: |
        flutter analyze
